/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_add_parking_window (void)
{
  GtkWidget *add_parking_window;
  GtkWidget *fixed2;
  GtkWidget *RK_entry_rue_ajouter;
  GtkObject *RK_spinbutton_nbplace_ajouter_adj;
  GtkWidget *RK_spinbutton_nbplace_ajouter;
  GtkWidget *RK_entry_nomparking_ajouter;
  GtkWidget *RK_entry_num_ajouter;
  GtkWidget *RK_entry_codepostal_ajouter;
  GtkWidget *RK_entry_ville_ajouter;
  GtkObject *RK_spinbutton_debut_ajouter_adj;
  GtkWidget *RK_spinbutton_debut_ajouter;
  GtkObject *RK_spinbutton_fin_ajouter_adj;
  GtkWidget *RK_spinbutton_fin_ajouter;
  GtkObject *RK_spinbutton_nbetage_ajouter_adj;
  GtkWidget *RK_spinbutton_nbetage_ajouter;
  GtkWidget *RK_entry_id_ajouter;
  GtkWidget *RK_entry_nomagent_ajouter;
  GtkWidget *RK_label_nomparking_ajouter;
  GtkWidget *RK_label_rue_ajouter;
  GtkWidget *RK_checkbutton_camera_ajouter;
  GtkWidget *RK_label_ouverture_ajouter;
  GtkWidget *RK_label_debut_ajouter;
  GtkWidget *RK_label_fin_ajouter;
  GtkWidget *RK_label_statut_ajouter;
  GtkWidget *RK_checkbutton_alarme_ajouter;
  GtkWidget *RK_label_id_ajouter;
  GtkWidget *RK_label_num_ajouter;
  GtkWidget *RK_label_codepostal_ajouter;
  GtkWidget *RK_label_ville_ajouter;
  GtkWidget *RK_checkbutton_commercial_ajouter;
  GtkWidget *RK_checkbutton_residentiel_ajouter;
  GtkWidget *RK_checkbutton_prive_ajouter;
  GtkWidget *RK_checkbutton_public_ajouter;
  GtkWidget *RK_label_type_ajouter;
  GtkWidget *RK_label_nbetage_ajouter;
  GtkWidget *RK_label_typeacces_ajouter;
  GtkWidget *RK_label_securite_ajouter;
  GtkWidget *RK_button_ajouter_ajouter;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image7;
  GtkWidget *label45;
  GtkWidget *RK_button_annuler_ajouter;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image8;
  GtkWidget *label46;
  GtkWidget *RK_label_nomagent_ajouter;
  GtkWidget *RK_checkbutton_gardien_ajouter;
  GtkWidget *RK_comboboxentry_statut_ajouter;
  GtkWidget *RK_comboboxentry_typeacces_ajouter;
  GtkObject *RK_spinbutton_nbplacereserve_ajouter_adj;
  GtkWidget *RK_spinbutton_nbplacereserve_ajouter;
  GtkWidget *RK_checkbutton_eclairage_ajouter;
  GtkWidget *RK_label_nbplace_ajouter;
  GtkWidget *RK_label_nbplacereserve_ajouter;
  GtkWidget *RK_label_message_ajouter;

  add_parking_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (add_parking_window), _("Ajouter un parking"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (add_parking_window), fixed2);

  RK_entry_rue_ajouter = gtk_entry_new ();
  gtk_widget_show (RK_entry_rue_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_entry_rue_ajouter, 160, 320);
  gtk_widget_set_size_request (RK_entry_rue_ajouter, 189, 29);
  gtk_entry_set_invisible_char (GTK_ENTRY (RK_entry_rue_ajouter), 8226);

  RK_spinbutton_nbplace_ajouter_adj = gtk_adjustment_new (1, 0, 1000, 1, 10, 0);
  RK_spinbutton_nbplace_ajouter = gtk_spin_button_new (GTK_ADJUSTMENT (RK_spinbutton_nbplace_ajouter_adj), 1, 0);
  gtk_widget_show (RK_spinbutton_nbplace_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_spinbutton_nbplace_ajouter, 216, 488);
  gtk_widget_set_size_request (RK_spinbutton_nbplace_ajouter, 189, 29);

  RK_entry_nomparking_ajouter = gtk_entry_new ();
  gtk_widget_show (RK_entry_nomparking_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_entry_nomparking_ajouter, 520, 232);
  gtk_widget_set_size_request (RK_entry_nomparking_ajouter, 189, 29);
  gtk_entry_set_invisible_char (GTK_ENTRY (RK_entry_nomparking_ajouter), 8226);

  RK_entry_num_ajouter = gtk_entry_new ();
  gtk_widget_show (RK_entry_num_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_entry_num_ajouter, 560, 312);
  gtk_widget_set_size_request (RK_entry_num_ajouter, 189, 29);
  gtk_entry_set_invisible_char (GTK_ENTRY (RK_entry_num_ajouter), 8226);

  RK_entry_codepostal_ajouter = gtk_entry_new ();
  gtk_widget_show (RK_entry_codepostal_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_entry_codepostal_ajouter, 880, 296);
  gtk_widget_set_size_request (RK_entry_codepostal_ajouter, 189, 29);
  gtk_entry_set_invisible_char (GTK_ENTRY (RK_entry_codepostal_ajouter), 8226);

  RK_entry_ville_ajouter = gtk_entry_new ();
  gtk_widget_show (RK_entry_ville_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_entry_ville_ajouter, 1208, 296);
  gtk_widget_set_size_request (RK_entry_ville_ajouter, 189, 29);
  gtk_entry_set_invisible_char (GTK_ENTRY (RK_entry_ville_ajouter), 8226);

  RK_spinbutton_debut_ajouter_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 0);
  RK_spinbutton_debut_ajouter = gtk_spin_button_new (GTK_ADJUSTMENT (RK_spinbutton_debut_ajouter_adj), 1, 0);
  gtk_widget_show (RK_spinbutton_debut_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_spinbutton_debut_ajouter, 352, 720);
  gtk_widget_set_size_request (RK_spinbutton_debut_ajouter, 60, 27);

  RK_spinbutton_fin_ajouter_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 0);
  RK_spinbutton_fin_ajouter = gtk_spin_button_new (GTK_ADJUSTMENT (RK_spinbutton_fin_ajouter_adj), 1, 0);
  gtk_widget_show (RK_spinbutton_fin_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_spinbutton_fin_ajouter, 592, 720);
  gtk_widget_set_size_request (RK_spinbutton_fin_ajouter, 60, 27);

  RK_spinbutton_nbetage_ajouter_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 0);
  RK_spinbutton_nbetage_ajouter = gtk_spin_button_new (GTK_ADJUSTMENT (RK_spinbutton_nbetage_ajouter_adj), 1, 0);
  gtk_widget_show (RK_spinbutton_nbetage_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_spinbutton_nbetage_ajouter, 216, 544);
  gtk_widget_set_size_request (RK_spinbutton_nbetage_ajouter, 189, 29);

  RK_entry_id_ajouter = gtk_entry_new ();
  gtk_widget_show (RK_entry_id_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_entry_id_ajouter, 160, 224);
  gtk_widget_set_size_request (RK_entry_id_ajouter, 189, 29);
  gtk_entry_set_invisible_char (GTK_ENTRY (RK_entry_id_ajouter), 8226);

  RK_entry_nomagent_ajouter = gtk_entry_new ();
  gtk_widget_show (RK_entry_nomagent_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_entry_nomagent_ajouter, 832, 232);
  gtk_widget_set_size_request (RK_entry_nomagent_ajouter, 189, 29);
  gtk_entry_set_text (GTK_ENTRY (RK_entry_nomagent_ajouter), _("auncun agent"));
  gtk_entry_set_invisible_char (GTK_ENTRY (RK_entry_nomagent_ajouter), 8226);

  RK_label_nomparking_ajouter = gtk_label_new (_("Nom du parking"));
  gtk_widget_show (RK_label_nomparking_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_label_nomparking_ajouter, 400, 240);
  gtk_widget_set_size_request (RK_label_nomparking_ajouter, 112, 16);

  RK_label_rue_ajouter = gtk_label_new (_("Rue"));
  gtk_widget_show (RK_label_rue_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_label_rue_ajouter, 56, 320);
  gtk_widget_set_size_request (RK_label_rue_ajouter, 89, 17);

  RK_checkbutton_camera_ajouter = gtk_check_button_new_with_mnemonic (_("Cam\303\251ras de surveillance"));
  gtk_widget_show (RK_checkbutton_camera_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_checkbutton_camera_ajouter, 216, 664);
  gtk_widget_set_size_request (RK_checkbutton_camera_ajouter, 216, 24);

  RK_label_ouverture_ajouter = gtk_label_new (_("Heures d'ouverture"));
  gtk_widget_show (RK_label_ouverture_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_label_ouverture_ajouter, 8, 728);
  gtk_widget_set_size_request (RK_label_ouverture_ajouter, 152, 25);

  RK_label_debut_ajouter = gtk_label_new (_("Heure de d\303\251but "));
  gtk_widget_show (RK_label_debut_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_label_debut_ajouter, 216, 728);
  gtk_widget_set_size_request (RK_label_debut_ajouter, 144, 16);

  RK_label_fin_ajouter = gtk_label_new (_("Heure de fin"));
  gtk_widget_show (RK_label_fin_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_label_fin_ajouter, 464, 728);
  gtk_widget_set_size_request (RK_label_fin_ajouter, 144, 16);

  RK_label_statut_ajouter = gtk_label_new (_("Statut actuel du parking"));
  gtk_widget_show (RK_label_statut_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_label_statut_ajouter, 0, 808);
  gtk_widget_set_size_request (RK_label_statut_ajouter, 184, 25);

  RK_checkbutton_alarme_ajouter = gtk_check_button_new_with_mnemonic (_("Syst\303\250me d'alarme"));
  gtk_widget_show (RK_checkbutton_alarme_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_checkbutton_alarme_ajouter, 480, 664);
  gtk_widget_set_size_request (RK_checkbutton_alarme_ajouter, 168, 24);

  RK_label_id_ajouter = gtk_label_new (_("id_parking"));
  gtk_widget_show (RK_label_id_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_label_id_ajouter, 40, 232);
  gtk_widget_set_size_request (RK_label_id_ajouter, 112, 16);

  RK_label_num_ajouter = gtk_label_new (_("Num\303\251ro"));
  gtk_widget_show (RK_label_num_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_label_num_ajouter, 456, 320);
  gtk_widget_set_size_request (RK_label_num_ajouter, 89, 17);

  RK_label_codepostal_ajouter = gtk_label_new (_("Code postal"));
  gtk_widget_show (RK_label_codepostal_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_label_codepostal_ajouter, 776, 304);
  gtk_widget_set_size_request (RK_label_codepostal_ajouter, 89, 17);

  RK_label_ville_ajouter = gtk_label_new (_("Ville"));
  gtk_widget_show (RK_label_ville_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_label_ville_ajouter, 1112, 304);
  gtk_widget_set_size_request (RK_label_ville_ajouter, 89, 17);

  RK_checkbutton_commercial_ajouter = gtk_check_button_new_with_mnemonic (_("Commercial"));
  gtk_widget_show (RK_checkbutton_commercial_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_checkbutton_commercial_ajouter, 856, 400);
  gtk_widget_set_size_request (RK_checkbutton_commercial_ajouter, 118, 24);

  RK_checkbutton_residentiel_ajouter = gtk_check_button_new_with_mnemonic (_("R\303\251sidentiel"));
  gtk_widget_show (RK_checkbutton_residentiel_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_checkbutton_residentiel_ajouter, 656, 400);
  gtk_widget_set_size_request (RK_checkbutton_residentiel_ajouter, 118, 24);

  RK_checkbutton_prive_ajouter = gtk_check_button_new_with_mnemonic (_("Priv\303\251"));
  gtk_widget_show (RK_checkbutton_prive_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_checkbutton_prive_ajouter, 472, 400);
  gtk_widget_set_size_request (RK_checkbutton_prive_ajouter, 118, 24);

  RK_checkbutton_public_ajouter = gtk_check_button_new_with_mnemonic (_("Public"));
  gtk_widget_show (RK_checkbutton_public_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_checkbutton_public_ajouter, 256, 400);
  gtk_widget_set_size_request (RK_checkbutton_public_ajouter, 118, 24);

  RK_label_type_ajouter = gtk_label_new (_("Type de parking"));
  gtk_widget_show (RK_label_type_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_label_type_ajouter, 16, 408);
  gtk_widget_set_size_request (RK_label_type_ajouter, 152, 16);

  RK_label_nbetage_ajouter = gtk_label_new (_("Nombre d'\303\251tages"));
  gtk_widget_show (RK_label_nbetage_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_label_nbetage_ajouter, 16, 552);
  gtk_widget_set_size_request (RK_label_nbetage_ajouter, 144, 16);

  RK_label_typeacces_ajouter = gtk_label_new (_("Type d'acc\303\250s"));
  gtk_widget_show (RK_label_typeacces_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_label_typeacces_ajouter, 8, 616);
  gtk_widget_set_size_request (RK_label_typeacces_ajouter, 144, 16);

  RK_label_securite_ajouter = gtk_label_new (_("Syst\303\250me de s\303\251curit\303\251"));
  gtk_widget_show (RK_label_securite_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_label_securite_ajouter, 16, 664);
  gtk_widget_set_size_request (RK_label_securite_ajouter, 144, 16);

  RK_button_ajouter_ajouter = gtk_button_new ();
  gtk_widget_show (RK_button_ajouter_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_button_ajouter_ajouter, 1584, 816);
  gtk_widget_set_size_request (RK_button_ajouter_ajouter, 104, 29);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (RK_button_ajouter_ajouter), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image7 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox6), image7, FALSE, FALSE, 0);

  label45 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox6), label45, FALSE, FALSE, 0);

  RK_button_annuler_ajouter = gtk_button_new ();
  gtk_widget_show (RK_button_annuler_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_button_annuler_ajouter, 1464, 816);
  gtk_widget_set_size_request (RK_button_annuler_ajouter, 90, 29);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (RK_button_annuler_ajouter), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image8 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox7), image8, FALSE, FALSE, 0);

  label46 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox7), label46, FALSE, FALSE, 0);

  RK_label_nomagent_ajouter = gtk_label_new (_("id agent"));
  gtk_widget_show (RK_label_nomagent_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_label_nomagent_ajouter, 728, 240);
  gtk_widget_set_size_request (RK_label_nomagent_ajouter, 112, 16);

  RK_checkbutton_gardien_ajouter = gtk_check_button_new_with_mnemonic (_(" Gardien de nuit"));
  gtk_widget_show (RK_checkbutton_gardien_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_checkbutton_gardien_ajouter, 688, 656);
  gtk_widget_set_size_request (RK_checkbutton_gardien_ajouter, 152, 24);

  RK_comboboxentry_statut_ajouter = gtk_combo_box_entry_new_text ();
  gtk_widget_show (RK_comboboxentry_statut_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_comboboxentry_statut_ajouter, 192, 808);
  gtk_widget_set_size_request (RK_comboboxentry_statut_ajouter, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (RK_comboboxentry_statut_ajouter), _("ouvert"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (RK_comboboxentry_statut_ajouter), _("ferme"));

  RK_comboboxentry_typeacces_ajouter = gtk_combo_box_entry_new_text ();
  gtk_widget_show (RK_comboboxentry_typeacces_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_comboboxentry_typeacces_ajouter, 216, 616);
  gtk_widget_set_size_request (RK_comboboxentry_typeacces_ajouter, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (RK_comboboxentry_typeacces_ajouter), _("libre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (RK_comboboxentry_typeacces_ajouter), _("mot de passe"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (RK_comboboxentry_typeacces_ajouter), _("code"));

  RK_spinbutton_nbplacereserve_ajouter_adj = gtk_adjustment_new (1, 0, 1000, 1, 10, 0);
  RK_spinbutton_nbplacereserve_ajouter = gtk_spin_button_new (GTK_ADJUSTMENT (RK_spinbutton_nbplacereserve_ajouter_adj), 1, 0);
  gtk_widget_show (RK_spinbutton_nbplacereserve_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_spinbutton_nbplacereserve_ajouter, 696, 488);
  gtk_widget_set_size_request (RK_spinbutton_nbplacereserve_ajouter, 189, 29);

  RK_checkbutton_eclairage_ajouter = gtk_check_button_new_with_mnemonic (_("\303\211clairage automatique"));
  gtk_widget_show (RK_checkbutton_eclairage_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_checkbutton_eclairage_ajouter, 928, 656);
  gtk_widget_set_size_request (RK_checkbutton_eclairage_ajouter, 192, 24);

  RK_label_nbplace_ajouter = gtk_label_new (_("Nombre de places "));
  gtk_widget_show (RK_label_nbplace_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_label_nbplace_ajouter, 24, 496);
  gtk_widget_set_size_request (RK_label_nbplace_ajouter, 144, 16);
  gtk_misc_set_alignment (GTK_MISC (RK_label_nbplace_ajouter), 0.77, 0.5);

  RK_label_nbplacereserve_ajouter = gtk_label_new (_("Nombre de places r\303\251serv\303\251s"));
  gtk_widget_show (RK_label_nbplacereserve_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_label_nbplacereserve_ajouter, 448, 496);
  gtk_widget_set_size_request (RK_label_nbplacereserve_ajouter, 264, 16);

  RK_label_message_ajouter = gtk_label_new (_("<span foreground=\"blue\" weight=\"bold\" size=\"xx-large\">Veuillez entrer les d\303\251tails du nouveau parking</span>\n"));
  gtk_widget_show (RK_label_message_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), RK_label_message_ajouter, 528, 48);
  gtk_widget_set_size_request (RK_label_message_ajouter, 624, 88);
  gtk_label_set_use_markup (GTK_LABEL (RK_label_message_ajouter), TRUE);

  g_signal_connect ((gpointer) RK_button_ajouter_ajouter, "clicked",
                    G_CALLBACK (on_RK_button_ajouter_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) RK_button_annuler_ajouter, "clicked",
                    G_CALLBACK (on_RK_button_annuler_ajouter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (add_parking_window, add_parking_window, "add_parking_window");
  GLADE_HOOKUP_OBJECT (add_parking_window, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_entry_rue_ajouter, "RK_entry_rue_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_spinbutton_nbplace_ajouter, "RK_spinbutton_nbplace_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_entry_nomparking_ajouter, "RK_entry_nomparking_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_entry_num_ajouter, "RK_entry_num_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_entry_codepostal_ajouter, "RK_entry_codepostal_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_entry_ville_ajouter, "RK_entry_ville_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_spinbutton_debut_ajouter, "RK_spinbutton_debut_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_spinbutton_fin_ajouter, "RK_spinbutton_fin_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_spinbutton_nbetage_ajouter, "RK_spinbutton_nbetage_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_entry_id_ajouter, "RK_entry_id_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_entry_nomagent_ajouter, "RK_entry_nomagent_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_label_nomparking_ajouter, "RK_label_nomparking_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_label_rue_ajouter, "RK_label_rue_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_checkbutton_camera_ajouter, "RK_checkbutton_camera_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_label_ouverture_ajouter, "RK_label_ouverture_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_label_debut_ajouter, "RK_label_debut_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_label_fin_ajouter, "RK_label_fin_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_label_statut_ajouter, "RK_label_statut_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_checkbutton_alarme_ajouter, "RK_checkbutton_alarme_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_label_id_ajouter, "RK_label_id_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_label_num_ajouter, "RK_label_num_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_label_codepostal_ajouter, "RK_label_codepostal_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_label_ville_ajouter, "RK_label_ville_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_checkbutton_commercial_ajouter, "RK_checkbutton_commercial_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_checkbutton_residentiel_ajouter, "RK_checkbutton_residentiel_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_checkbutton_prive_ajouter, "RK_checkbutton_prive_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_checkbutton_public_ajouter, "RK_checkbutton_public_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_label_type_ajouter, "RK_label_type_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_label_nbetage_ajouter, "RK_label_nbetage_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_label_typeacces_ajouter, "RK_label_typeacces_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_label_securite_ajouter, "RK_label_securite_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_button_ajouter_ajouter, "RK_button_ajouter_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (add_parking_window, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (add_parking_window, image7, "image7");
  GLADE_HOOKUP_OBJECT (add_parking_window, label45, "label45");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_button_annuler_ajouter, "RK_button_annuler_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (add_parking_window, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (add_parking_window, image8, "image8");
  GLADE_HOOKUP_OBJECT (add_parking_window, label46, "label46");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_label_nomagent_ajouter, "RK_label_nomagent_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_checkbutton_gardien_ajouter, "RK_checkbutton_gardien_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_comboboxentry_statut_ajouter, "RK_comboboxentry_statut_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_comboboxentry_typeacces_ajouter, "RK_comboboxentry_typeacces_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_spinbutton_nbplacereserve_ajouter, "RK_spinbutton_nbplacereserve_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_checkbutton_eclairage_ajouter, "RK_checkbutton_eclairage_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_label_nbplace_ajouter, "RK_label_nbplace_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_label_nbplacereserve_ajouter, "RK_label_nbplacereserve_ajouter");
  GLADE_HOOKUP_OBJECT (add_parking_window, RK_label_message_ajouter, "RK_label_message_ajouter");

  return add_parking_window;
}

GtkWidget*
create_edit_parking_window (void)
{
  GtkWidget *edit_parking_window;
  GtkWidget *fixed16;
  GtkWidget *RK_entry_rue_modifier;
  GtkObject *RK_spinbutton_nbetage_modifier_adj;
  GtkWidget *RK_spinbutton_nbetage_modifier;
  GtkWidget *label_feedback;
  GtkWidget *RK_entry_num_modifier;
  GtkWidget *RK_entry_codepostal_modifier;
  GtkWidget *RK_entry_ville_modifier;
  GtkObject *RK_spinbutton_nbplace_modifier_adj;
  GtkWidget *RK_spinbutton_nbplace_modifier;
  GtkObject *RK_spinbutton_debut_modifier_adj;
  GtkWidget *RK_spinbutton_debut_modifier;
  GtkObject *RK_spinbutton_fin_modifier_adj;
  GtkWidget *RK_spinbutton_fin_modifier;
  GtkWidget *RK_entry_nomparking_modifier;
  GtkWidget *RK_entry_id_modifier;
  GtkWidget *RK_label_rue_ajouter;
  GtkWidget *RK_label_num_modifier;
  GtkWidget *RK_label_codepostal_modifier;
  GtkWidget *RK_label_ville_modifier;
  GtkWidget *RK_label_type_modifier;
  GtkWidget *RK_label_nbetage_modifier;
  GtkWidget *RK_label_typeacces_modifier;
  GtkWidget *RK_label_securite_modifier;
  GtkWidget *RK_label_ouverture_modifier;
  GtkWidget *RK_label_debut_modifier;
  GtkWidget *RK_label_fin_modifier;
  GtkWidget *RK_label_statut_modifier;
  GtkWidget *RK_checkbutton_alarme_modifier;
  GtkWidget *RK_checkbutton_gardien_modifier;
  GtkWidget *RK_checkbutton_eclairage_modifier;
  GtkWidget *RK_checkbutton_camera_modifier;
  GtkWidget *RK_checkbutton_public_modifier;
  GtkWidget *RK_comboboxentry_typeacces_modifier;
  GtkWidget *RK_label_id_modifier;
  GtkWidget *RK_label_label_modifier;
  GtkWidget *RK_checkbutton_residentiel_modifier;
  GtkWidget *RK_checkbutton_prive_modifier;
  GtkWidget *RK_checkbutton_commercial_modifier;
  GtkWidget *RK_button_modifier_modifier;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image2;
  GtkWidget *label40;
  GtkWidget *RK_button_annuler_modifier;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image3;
  GtkWidget *label41;
  GtkWidget *RK_label_nomparking_modifier;
  GtkWidget *label126;
  GtkWidget *RK_entry_nomagent_modifier;
  GtkWidget *RK_button_chercher_modifier;
  GtkWidget *alignment34;
  GtkWidget *hbox34;
  GtkWidget *image36;
  GtkWidget *label123;
  GtkWidget *RK_comboboxentry_statut_modifier;
  GtkWidget *label39;
  GtkObject *RK_spinbutton_nbplacereservee_modifier_adj;
  GtkWidget *RK_spinbutton_nbplacereservee_modifier;
  GtkWidget *label131;
  GtkWidget *RK_label_nbplace_modifier;

  edit_parking_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (edit_parking_window), _("Modifier un parking"));

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (edit_parking_window), fixed16);

  RK_entry_rue_modifier = gtk_entry_new ();
  gtk_widget_show (RK_entry_rue_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_entry_rue_modifier, 168, 392);
  gtk_widget_set_size_request (RK_entry_rue_modifier, 189, 29);
  gtk_entry_set_invisible_char (GTK_ENTRY (RK_entry_rue_modifier), 8226);

  RK_spinbutton_nbetage_modifier_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 0);
  RK_spinbutton_nbetage_modifier = gtk_spin_button_new (GTK_ADJUSTMENT (RK_spinbutton_nbetage_modifier_adj), 1, 0);
  gtk_widget_show (RK_spinbutton_nbetage_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_spinbutton_nbetage_modifier, 208, 560);
  gtk_widget_set_size_request (RK_spinbutton_nbetage_modifier, 189, 29);

  label_feedback = gtk_label_new (_("\"\""));
  gtk_widget_show (label_feedback);
  gtk_fixed_put (GTK_FIXED (fixed16), label_feedback, 248, 328);
  gtk_widget_set_size_request (label_feedback, 49, 17);

  RK_entry_num_modifier = gtk_entry_new ();
  gtk_widget_show (RK_entry_num_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_entry_num_modifier, 520, 384);
  gtk_widget_set_size_request (RK_entry_num_modifier, 189, 29);
  gtk_entry_set_invisible_char (GTK_ENTRY (RK_entry_num_modifier), 8226);

  RK_entry_codepostal_modifier = gtk_entry_new ();
  gtk_widget_show (RK_entry_codepostal_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_entry_codepostal_modifier, 864, 376);
  gtk_widget_set_size_request (RK_entry_codepostal_modifier, 189, 29);
  gtk_entry_set_invisible_char (GTK_ENTRY (RK_entry_codepostal_modifier), 8226);

  RK_entry_ville_modifier = gtk_entry_new ();
  gtk_widget_show (RK_entry_ville_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_entry_ville_modifier, 1168, 376);
  gtk_widget_set_size_request (RK_entry_ville_modifier, 189, 29);
  gtk_entry_set_invisible_char (GTK_ENTRY (RK_entry_ville_modifier), 8226);

  RK_spinbutton_nbplace_modifier_adj = gtk_adjustment_new (1, 0, 1000, 1, 10, 0);
  RK_spinbutton_nbplace_modifier = gtk_spin_button_new (GTK_ADJUSTMENT (RK_spinbutton_nbplace_modifier_adj), 1, 0);
  gtk_widget_show (RK_spinbutton_nbplace_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_spinbutton_nbplace_modifier, 200, 512);
  gtk_widget_set_size_request (RK_spinbutton_nbplace_modifier, 189, 29);

  RK_spinbutton_debut_modifier_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 0);
  RK_spinbutton_debut_modifier = gtk_spin_button_new (GTK_ADJUSTMENT (RK_spinbutton_debut_modifier_adj), 1, 0);
  gtk_widget_show (RK_spinbutton_debut_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_spinbutton_debut_modifier, 360, 720);
  gtk_widget_set_size_request (RK_spinbutton_debut_modifier, 60, 27);

  RK_spinbutton_fin_modifier_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 0);
  RK_spinbutton_fin_modifier = gtk_spin_button_new (GTK_ADJUSTMENT (RK_spinbutton_fin_modifier_adj), 1, 0);
  gtk_widget_show (RK_spinbutton_fin_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_spinbutton_fin_modifier, 640, 720);
  gtk_widget_set_size_request (RK_spinbutton_fin_modifier, 60, 27);

  RK_entry_nomparking_modifier = gtk_entry_new ();
  gtk_widget_show (RK_entry_nomparking_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_entry_nomparking_modifier, 176, 320);
  gtk_widget_set_size_request (RK_entry_nomparking_modifier, 189, 29);
  gtk_entry_set_invisible_char (GTK_ENTRY (RK_entry_nomparking_modifier), 8226);

  RK_entry_id_modifier = gtk_entry_new ();
  gtk_widget_show (RK_entry_id_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_entry_id_modifier, 640, 144);
  gtk_widget_set_size_request (RK_entry_id_modifier, 189, 29);
  gtk_entry_set_invisible_char (GTK_ENTRY (RK_entry_id_modifier), 8226);

  RK_label_rue_ajouter = gtk_label_new (_("Rue"));
  gtk_widget_show (RK_label_rue_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_label_rue_ajouter, 24, 392);
  gtk_widget_set_size_request (RK_label_rue_ajouter, 89, 17);

  RK_label_num_modifier = gtk_label_new (_("Num\303\251ro"));
  gtk_widget_show (RK_label_num_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_label_num_modifier, 440, 392);
  gtk_widget_set_size_request (RK_label_num_modifier, 89, 17);

  RK_label_codepostal_modifier = gtk_label_new (_("Code postal"));
  gtk_widget_show (RK_label_codepostal_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_label_codepostal_modifier, 776, 384);
  gtk_widget_set_size_request (RK_label_codepostal_modifier, 89, 17);

  RK_label_ville_modifier = gtk_label_new (_("Ville"));
  gtk_widget_show (RK_label_ville_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_label_ville_modifier, 1104, 384);
  gtk_widget_set_size_request (RK_label_ville_modifier, 89, 17);

  RK_label_type_modifier = gtk_label_new (_("Type de parking"));
  gtk_widget_show (RK_label_type_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_label_type_modifier, 0, 464);
  gtk_widget_set_size_request (RK_label_type_modifier, 152, 16);

  RK_label_nbetage_modifier = gtk_label_new (_("Nombre d'\303\251tages"));
  gtk_widget_show (RK_label_nbetage_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_label_nbetage_modifier, 24, 576);
  gtk_widget_set_size_request (RK_label_nbetage_modifier, 144, 16);

  RK_label_typeacces_modifier = gtk_label_new (_("Type d'acc\303\250s"));
  gtk_widget_show (RK_label_typeacces_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_label_typeacces_modifier, 24, 624);
  gtk_widget_set_size_request (RK_label_typeacces_modifier, 144, 16);

  RK_label_securite_modifier = gtk_label_new (_("Syst\303\250me de s\303\251curit\303\251"));
  gtk_widget_show (RK_label_securite_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_label_securite_modifier, 40, 672);
  gtk_widget_set_size_request (RK_label_securite_modifier, 144, 16);

  RK_label_ouverture_modifier = gtk_label_new (_("Heures d'ouverture"));
  gtk_widget_show (RK_label_ouverture_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_label_ouverture_modifier, 32, 720);
  gtk_widget_set_size_request (RK_label_ouverture_modifier, 152, 25);

  RK_label_debut_modifier = gtk_label_new (_("Heure de d\303\251but "));
  gtk_widget_show (RK_label_debut_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_label_debut_modifier, 216, 728);
  gtk_widget_set_size_request (RK_label_debut_modifier, 144, 16);

  RK_label_fin_modifier = gtk_label_new (_("Heure de fin"));
  gtk_widget_show (RK_label_fin_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_label_fin_modifier, 504, 728);
  gtk_widget_set_size_request (RK_label_fin_modifier, 144, 16);

  RK_label_statut_modifier = gtk_label_new (_("Statut actuel du parking"));
  gtk_widget_show (RK_label_statut_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_label_statut_modifier, 24, 776);
  gtk_widget_set_size_request (RK_label_statut_modifier, 184, 25);

  RK_checkbutton_alarme_modifier = gtk_check_button_new_with_mnemonic (_("Alarme"));
  gtk_widget_show (RK_checkbutton_alarme_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_checkbutton_alarme_modifier, 512, 656);
  gtk_widget_set_size_request (RK_checkbutton_alarme_modifier, 168, 24);

  RK_checkbutton_gardien_modifier = gtk_check_button_new_with_mnemonic (_(" Gardien de nuit"));
  gtk_widget_show (RK_checkbutton_gardien_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_checkbutton_gardien_modifier, 768, 648);
  gtk_widget_set_size_request (RK_checkbutton_gardien_modifier, 152, 24);

  RK_checkbutton_eclairage_modifier = gtk_check_button_new_with_mnemonic (_("\303\211clairage automatique"));
  gtk_widget_show (RK_checkbutton_eclairage_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_checkbutton_eclairage_modifier, 1024, 648);
  gtk_widget_set_size_request (RK_checkbutton_eclairage_modifier, 192, 24);

  RK_checkbutton_camera_modifier = gtk_check_button_new_with_mnemonic (_("Cam\303\251ras de surveillance"));
  gtk_widget_show (RK_checkbutton_camera_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_checkbutton_camera_modifier, 248, 664);
  gtk_widget_set_size_request (RK_checkbutton_camera_modifier, 216, 24);

  RK_checkbutton_public_modifier = gtk_check_button_new_with_mnemonic (_("Public"));
  gtk_widget_show (RK_checkbutton_public_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_checkbutton_public_modifier, 200, 456);
  gtk_widget_set_size_request (RK_checkbutton_public_modifier, 118, 24);

  RK_comboboxentry_typeacces_modifier = gtk_combo_box_entry_new_text ();
  gtk_widget_show (RK_comboboxentry_typeacces_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_comboboxentry_typeacces_modifier, 200, 616);
  gtk_widget_set_size_request (RK_comboboxentry_typeacces_modifier, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (RK_comboboxentry_typeacces_modifier), _("libre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (RK_comboboxentry_typeacces_modifier), _("mot de passe"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (RK_comboboxentry_typeacces_modifier), _("code"));

  RK_label_id_modifier = gtk_label_new (_("id_parking"));
  gtk_widget_show (RK_label_id_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_label_id_modifier, 512, 144);
  gtk_widget_set_size_request (RK_label_id_modifier, 168, 25);

  RK_label_label_modifier = gtk_label_new ("");
  gtk_widget_show (RK_label_label_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_label_label_modifier, 576, 224);
  gtk_widget_set_size_request (RK_label_label_modifier, 408, 33);

  RK_checkbutton_residentiel_modifier = gtk_check_button_new_with_mnemonic (_("R\303\251sidentiel"));
  gtk_widget_show (RK_checkbutton_residentiel_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_checkbutton_residentiel_modifier, 568, 456);
  gtk_widget_set_size_request (RK_checkbutton_residentiel_modifier, 118, 24);

  RK_checkbutton_prive_modifier = gtk_check_button_new_with_mnemonic (_("Priv\303\251"));
  gtk_widget_show (RK_checkbutton_prive_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_checkbutton_prive_modifier, 384, 456);
  gtk_widget_set_size_request (RK_checkbutton_prive_modifier, 118, 24);

  RK_checkbutton_commercial_modifier = gtk_check_button_new_with_mnemonic (_("Commercial"));
  gtk_widget_show (RK_checkbutton_commercial_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_checkbutton_commercial_modifier, 752, 456);
  gtk_widget_set_size_request (RK_checkbutton_commercial_modifier, 118, 24);

  RK_button_modifier_modifier = gtk_button_new ();
  gtk_widget_show (RK_button_modifier_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_button_modifier_modifier, 1592, 808);
  gtk_widget_set_size_request (RK_button_modifier_modifier, 120, 29);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (RK_button_modifier_modifier), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image2 = gtk_image_new_from_icon_name ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox1), image2, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("Mettre \303\240 jour"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox1), label40, FALSE, FALSE, 0);

  RK_button_annuler_modifier = gtk_button_new ();
  gtk_widget_show (RK_button_annuler_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_button_annuler_modifier, 1480, 808);
  gtk_widget_set_size_request (RK_button_annuler_modifier, 90, 29);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (RK_button_annuler_modifier), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image3 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox2), image3, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox2), label41, FALSE, FALSE, 0);

  RK_label_nomparking_modifier = gtk_label_new (_("Nom du parking"));
  gtk_widget_show (RK_label_nomparking_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_label_nomparking_modifier, 0, 320);
  gtk_widget_set_size_request (RK_label_nomparking_modifier, 168, 25);

  label126 = gtk_label_new (_("id agent"));
  gtk_widget_show (label126);
  gtk_fixed_put (GTK_FIXED (fixed16), label126, 424, 320);
  gtk_widget_set_size_request (label126, 168, 25);

  RK_entry_nomagent_modifier = gtk_entry_new ();
  gtk_widget_show (RK_entry_nomagent_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_entry_nomagent_modifier, 544, 320);
  gtk_widget_set_size_request (RK_entry_nomagent_modifier, 189, 29);
  gtk_entry_set_text (GTK_ENTRY (RK_entry_nomagent_modifier), _("    agent non modifiable"));
  gtk_entry_set_invisible_char (GTK_ENTRY (RK_entry_nomagent_modifier), 8226);

  RK_button_chercher_modifier = gtk_button_new ();
  gtk_widget_show (RK_button_chercher_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_button_chercher_modifier, 880, 144);
  gtk_widget_set_size_request (RK_button_chercher_modifier, 160, 29);

  alignment34 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment34);
  gtk_container_add (GTK_CONTAINER (RK_button_chercher_modifier), alignment34);

  hbox34 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox34);
  gtk_container_add (GTK_CONTAINER (alignment34), hbox34);

  image36 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image36);
  gtk_box_pack_start (GTK_BOX (hbox34), image36, FALSE, FALSE, 0);

  label123 = gtk_label_new_with_mnemonic (_("chercher"));
  gtk_widget_show (label123);
  gtk_box_pack_start (GTK_BOX (hbox34), label123, FALSE, FALSE, 0);

  RK_comboboxentry_statut_modifier = gtk_combo_box_entry_new_text ();
  gtk_widget_show (RK_comboboxentry_statut_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_comboboxentry_statut_modifier, 216, 776);
  gtk_widget_set_size_request (RK_comboboxentry_statut_modifier, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (RK_comboboxentry_statut_modifier), _("ouvert"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (RK_comboboxentry_statut_modifier), _("ferme"));

  label39 = gtk_label_new (_("<span foreground=\"blue\" weight=\"bold\" size=\"xx-large\">Modifiez les d\303\251tails du parking s\303\251lectionn\303\251</span>\n"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed16), label39, 512, 16);
  gtk_widget_set_size_request (label39, 656, 80);
  gtk_label_set_use_markup (GTK_LABEL (label39), TRUE);

  RK_spinbutton_nbplacereservee_modifier_adj = gtk_adjustment_new (1, 0, 1000, 1, 10, 0);
  RK_spinbutton_nbplacereservee_modifier = gtk_spin_button_new (GTK_ADJUSTMENT (RK_spinbutton_nbplacereservee_modifier_adj), 1, 0);
  gtk_widget_show (RK_spinbutton_nbplacereservee_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_spinbutton_nbplacereservee_modifier, 680, 512);
  gtk_widget_set_size_request (RK_spinbutton_nbplacereservee_modifier, 189, 29);

  label131 = gtk_label_new (_("Nombre de places r\303\251serv\303\251s"));
  gtk_widget_show (label131);
  gtk_fixed_put (GTK_FIXED (fixed16), label131, 448, 520);
  gtk_widget_set_size_request (label131, 224, 16);

  RK_label_nbplace_modifier = gtk_label_new (_("Nombre de places "));
  gtk_widget_show (RK_label_nbplace_modifier);
  gtk_fixed_put (GTK_FIXED (fixed16), RK_label_nbplace_modifier, 32, 520);
  gtk_widget_set_size_request (RK_label_nbplace_modifier, 144, 16);

  g_signal_connect ((gpointer) RK_button_modifier_modifier, "clicked",
                    G_CALLBACK (on_RK_button_modifier_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) RK_button_annuler_modifier, "clicked",
                    G_CALLBACK (on_RK_button_annuler_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) RK_button_chercher_modifier, "clicked",
                    G_CALLBACK (on_RK_button_chercher_modifier_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (edit_parking_window, edit_parking_window, "edit_parking_window");
  GLADE_HOOKUP_OBJECT (edit_parking_window, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_entry_rue_modifier, "RK_entry_rue_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_spinbutton_nbetage_modifier, "RK_spinbutton_nbetage_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, label_feedback, "label_feedback");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_entry_num_modifier, "RK_entry_num_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_entry_codepostal_modifier, "RK_entry_codepostal_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_entry_ville_modifier, "RK_entry_ville_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_spinbutton_nbplace_modifier, "RK_spinbutton_nbplace_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_spinbutton_debut_modifier, "RK_spinbutton_debut_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_spinbutton_fin_modifier, "RK_spinbutton_fin_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_entry_nomparking_modifier, "RK_entry_nomparking_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_entry_id_modifier, "RK_entry_id_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_label_rue_ajouter, "RK_label_rue_ajouter");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_label_num_modifier, "RK_label_num_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_label_codepostal_modifier, "RK_label_codepostal_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_label_ville_modifier, "RK_label_ville_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_label_type_modifier, "RK_label_type_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_label_nbetage_modifier, "RK_label_nbetage_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_label_typeacces_modifier, "RK_label_typeacces_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_label_securite_modifier, "RK_label_securite_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_label_ouverture_modifier, "RK_label_ouverture_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_label_debut_modifier, "RK_label_debut_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_label_fin_modifier, "RK_label_fin_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_label_statut_modifier, "RK_label_statut_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_checkbutton_alarme_modifier, "RK_checkbutton_alarme_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_checkbutton_gardien_modifier, "RK_checkbutton_gardien_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_checkbutton_eclairage_modifier, "RK_checkbutton_eclairage_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_checkbutton_camera_modifier, "RK_checkbutton_camera_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_checkbutton_public_modifier, "RK_checkbutton_public_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_comboboxentry_typeacces_modifier, "RK_comboboxentry_typeacces_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_label_id_modifier, "RK_label_id_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_label_label_modifier, "RK_label_label_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_checkbutton_residentiel_modifier, "RK_checkbutton_residentiel_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_checkbutton_prive_modifier, "RK_checkbutton_prive_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_checkbutton_commercial_modifier, "RK_checkbutton_commercial_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_button_modifier_modifier, "RK_button_modifier_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (edit_parking_window, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (edit_parking_window, image2, "image2");
  GLADE_HOOKUP_OBJECT (edit_parking_window, label40, "label40");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_button_annuler_modifier, "RK_button_annuler_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (edit_parking_window, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (edit_parking_window, image3, "image3");
  GLADE_HOOKUP_OBJECT (edit_parking_window, label41, "label41");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_label_nomparking_modifier, "RK_label_nomparking_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, label126, "label126");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_entry_nomagent_modifier, "RK_entry_nomagent_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_button_chercher_modifier, "RK_button_chercher_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, alignment34, "alignment34");
  GLADE_HOOKUP_OBJECT (edit_parking_window, hbox34, "hbox34");
  GLADE_HOOKUP_OBJECT (edit_parking_window, image36, "image36");
  GLADE_HOOKUP_OBJECT (edit_parking_window, label123, "label123");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_comboboxentry_statut_modifier, "RK_comboboxentry_statut_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, label39, "label39");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_spinbutton_nbplacereservee_modifier, "RK_spinbutton_nbplacereservee_modifier");
  GLADE_HOOKUP_OBJECT (edit_parking_window, label131, "label131");
  GLADE_HOOKUP_OBJECT (edit_parking_window, RK_label_nbplace_modifier, "RK_label_nbplace_modifier");

  return edit_parking_window;
}

GtkWidget*
create_main_window (void)
{
  GtkWidget *main_window;
  GtkWidget *fixed15;
  GtkWidget *RK_button_ajouter_main;
  GtkWidget *alignment31;
  GtkWidget *hbox31;
  GtkWidget *image33;
  GtkWidget *label117;
  GtkWidget *RK_button_afficher_main;
  GtkWidget *alignment32;
  GtkWidget *hbox32;
  GtkWidget *image34;
  GtkWidget *label118;
  GtkWidget *RK_button_modifier_main;
  GtkWidget *alignment35;
  GtkWidget *hbox35;
  GtkWidget *image37;
  GtkWidget *label125;
  GtkWidget *RK_button_affecter_main;
  GtkWidget *alignment33;
  GtkWidget *hbox33;
  GtkWidget *image35;
  GtkWidget *label119;
  GtkWidget *label128;

  main_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (main_window), _("Gestion des parkings"));

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (main_window), fixed15);

  RK_button_ajouter_main = gtk_button_new ();
  gtk_widget_show (RK_button_ajouter_main);
  gtk_fixed_put (GTK_FIXED (fixed15), RK_button_ajouter_main, 632, 296);
  gtk_widget_set_size_request (RK_button_ajouter_main, 144, 37);

  alignment31 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment31);
  gtk_container_add (GTK_CONTAINER (RK_button_ajouter_main), alignment31);

  hbox31 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox31);
  gtk_container_add (GTK_CONTAINER (alignment31), hbox31);

  image33 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image33);
  gtk_box_pack_start (GTK_BOX (hbox31), image33, FALSE, FALSE, 0);

  label117 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label117);
  gtk_box_pack_start (GTK_BOX (hbox31), label117, FALSE, FALSE, 0);

  RK_button_afficher_main = gtk_button_new ();
  gtk_widget_show (RK_button_afficher_main);
  gtk_fixed_put (GTK_FIXED (fixed15), RK_button_afficher_main, 808, 296);
  gtk_widget_set_size_request (RK_button_afficher_main, 144, 37);

  alignment32 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment32);
  gtk_container_add (GTK_CONTAINER (RK_button_afficher_main), alignment32);

  hbox32 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox32);
  gtk_container_add (GTK_CONTAINER (alignment32), hbox32);

  image34 = gtk_image_new_from_stock ("gtk-orientation-landscape", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image34);
  gtk_box_pack_start (GTK_BOX (hbox32), image34, FALSE, FALSE, 0);

  label118 = gtk_label_new_with_mnemonic (_("afficher"));
  gtk_widget_show (label118);
  gtk_box_pack_start (GTK_BOX (hbox32), label118, FALSE, FALSE, 0);

  RK_button_modifier_main = gtk_button_new ();
  gtk_widget_show (RK_button_modifier_main);
  gtk_fixed_put (GTK_FIXED (fixed15), RK_button_modifier_main, 472, 296);
  gtk_widget_set_size_request (RK_button_modifier_main, 138, 37);

  alignment35 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment35);
  gtk_container_add (GTK_CONTAINER (RK_button_modifier_main), alignment35);

  hbox35 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox35);
  gtk_container_add (GTK_CONTAINER (alignment35), hbox35);

  image37 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image37);
  gtk_box_pack_start (GTK_BOX (hbox35), image37, FALSE, FALSE, 0);

  label125 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label125);
  gtk_box_pack_start (GTK_BOX (hbox35), label125, FALSE, FALSE, 0);

  RK_button_affecter_main = gtk_button_new ();
  gtk_widget_show (RK_button_affecter_main);
  gtk_fixed_put (GTK_FIXED (fixed15), RK_button_affecter_main, 968, 296);
  gtk_widget_set_size_request (RK_button_affecter_main, 160, 37);

  alignment33 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment33);
  gtk_container_add (GTK_CONTAINER (RK_button_affecter_main), alignment33);

  hbox33 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox33);
  gtk_container_add (GTK_CONTAINER (alignment33), hbox33);

  image35 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image35);
  gtk_box_pack_start (GTK_BOX (hbox33), image35, FALSE, FALSE, 0);

  label119 = gtk_label_new_with_mnemonic (_("affecter"));
  gtk_widget_show (label119);
  gtk_box_pack_start (GTK_BOX (hbox33), label119, FALSE, FALSE, 0);

  label128 = gtk_label_new (_("<span foreground=\"blue\" weight=\"bold\" size=\"xx-large\">Bienvenue \303\240 la Gestion des Parkings</span>\n"));
  gtk_widget_show (label128);
  gtk_fixed_put (GTK_FIXED (fixed15), label128, 552, 48);
  gtk_widget_set_size_request (label128, 500, 41);
  gtk_label_set_use_markup (GTK_LABEL (label128), TRUE);

  g_signal_connect ((gpointer) RK_button_ajouter_main, "clicked",
                    G_CALLBACK (on_RK_button_ajouter_main_clicked),
                    NULL);
  g_signal_connect ((gpointer) RK_button_afficher_main, "clicked",
                    G_CALLBACK (on_RK_button_afficher_main_clicked),
                    NULL);
  g_signal_connect ((gpointer) RK_button_modifier_main, "clicked",
                    G_CALLBACK (on_RK_button_modifier_main_clicked),
                    NULL);
  g_signal_connect ((gpointer) RK_button_affecter_main, "clicked",
                    G_CALLBACK (on_RK_button_affecter_main_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (main_window, main_window, "main_window");
  GLADE_HOOKUP_OBJECT (main_window, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (main_window, RK_button_ajouter_main, "RK_button_ajouter_main");
  GLADE_HOOKUP_OBJECT (main_window, alignment31, "alignment31");
  GLADE_HOOKUP_OBJECT (main_window, hbox31, "hbox31");
  GLADE_HOOKUP_OBJECT (main_window, image33, "image33");
  GLADE_HOOKUP_OBJECT (main_window, label117, "label117");
  GLADE_HOOKUP_OBJECT (main_window, RK_button_afficher_main, "RK_button_afficher_main");
  GLADE_HOOKUP_OBJECT (main_window, alignment32, "alignment32");
  GLADE_HOOKUP_OBJECT (main_window, hbox32, "hbox32");
  GLADE_HOOKUP_OBJECT (main_window, image34, "image34");
  GLADE_HOOKUP_OBJECT (main_window, label118, "label118");
  GLADE_HOOKUP_OBJECT (main_window, RK_button_modifier_main, "RK_button_modifier_main");
  GLADE_HOOKUP_OBJECT (main_window, alignment35, "alignment35");
  GLADE_HOOKUP_OBJECT (main_window, hbox35, "hbox35");
  GLADE_HOOKUP_OBJECT (main_window, image37, "image37");
  GLADE_HOOKUP_OBJECT (main_window, label125, "label125");
  GLADE_HOOKUP_OBJECT (main_window, RK_button_affecter_main, "RK_button_affecter_main");
  GLADE_HOOKUP_OBJECT (main_window, alignment33, "alignment33");
  GLADE_HOOKUP_OBJECT (main_window, hbox33, "hbox33");
  GLADE_HOOKUP_OBJECT (main_window, image35, "image35");
  GLADE_HOOKUP_OBJECT (main_window, label119, "label119");
  GLADE_HOOKUP_OBJECT (main_window, label128, "label128");

  return main_window;
}

GtkWidget*
create_show_parkings_window (void)
{
  GtkWidget *show_parkings_window;
  GtkWidget *fixed13;
  GtkWidget *RK_treeview_afficherparking_afficher;
  GtkWidget *RK_label_afficherparking_afficher;
  GtkWidget *RK_button_supprimer_afficher;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image18;
  GtkWidget *label68;
  GtkWidget *RK_button_fermer_afficher;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image6;
  GtkWidget *label44;
  GtkWidget *label129;

  show_parkings_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (show_parkings_window), _("Afficher les parkings"));
  gtk_window_set_modal (GTK_WINDOW (show_parkings_window), TRUE);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (show_parkings_window), fixed13);

  RK_treeview_afficherparking_afficher = gtk_tree_view_new ();
  gtk_widget_show (RK_treeview_afficherparking_afficher);
  gtk_fixed_put (GTK_FIXED (fixed13), RK_treeview_afficherparking_afficher, 272, 152);
  gtk_widget_set_size_request (RK_treeview_afficherparking_afficher, 1544, 600);

  RK_label_afficherparking_afficher = gtk_label_new ("");
  gtk_widget_show (RK_label_afficherparking_afficher);
  gtk_fixed_put (GTK_FIXED (fixed13), RK_label_afficherparking_afficher, 816, 704);
  gtk_widget_set_size_request (RK_label_afficherparking_afficher, 512, 32);

  RK_button_supprimer_afficher = gtk_button_new ();
  gtk_widget_show (RK_button_supprimer_afficher);
  gtk_fixed_put (GTK_FIXED (fixed13), RK_button_supprimer_afficher, 2032, 792);
  gtk_widget_set_size_request (RK_button_supprimer_afficher, 112, 29);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (RK_button_supprimer_afficher), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image18 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox17), image18, FALSE, FALSE, 0);

  label68 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label68);
  gtk_box_pack_start (GTK_BOX (hbox17), label68, FALSE, FALSE, 0);

  RK_button_fermer_afficher = gtk_button_new ();
  gtk_widget_show (RK_button_fermer_afficher);
  gtk_fixed_put (GTK_FIXED (fixed13), RK_button_fermer_afficher, 1936, 792);
  gtk_widget_set_size_request (RK_button_fermer_afficher, 90, 29);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (RK_button_fermer_afficher), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image6 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox5), image6, FALSE, FALSE, 0);

  label44 = gtk_label_new_with_mnemonic (_("Fermer"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox5), label44, FALSE, FALSE, 0);

  label129 = gtk_label_new (_("<span foreground=\"blue\" weight=\"bold\" size=\"xx-large\">Liste des parkings</span>\n"));
  gtk_widget_show (label129);
  gtk_fixed_put (GTK_FIXED (fixed13), label129, 632, 48);
  gtk_widget_set_size_request (label129, 784, 72);
  gtk_label_set_use_markup (GTK_LABEL (label129), TRUE);

  g_signal_connect ((gpointer) RK_button_supprimer_afficher, "clicked",
                    G_CALLBACK (on_RK_button_supprimer_afficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) RK_button_fermer_afficher, "clicked",
                    G_CALLBACK (on_RK_button_fermer_afficher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (show_parkings_window, show_parkings_window, "show_parkings_window");
  GLADE_HOOKUP_OBJECT (show_parkings_window, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (show_parkings_window, RK_treeview_afficherparking_afficher, "RK_treeview_afficherparking_afficher");
  GLADE_HOOKUP_OBJECT (show_parkings_window, RK_label_afficherparking_afficher, "RK_label_afficherparking_afficher");
  GLADE_HOOKUP_OBJECT (show_parkings_window, RK_button_supprimer_afficher, "RK_button_supprimer_afficher");
  GLADE_HOOKUP_OBJECT (show_parkings_window, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (show_parkings_window, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (show_parkings_window, image18, "image18");
  GLADE_HOOKUP_OBJECT (show_parkings_window, label68, "label68");
  GLADE_HOOKUP_OBJECT (show_parkings_window, RK_button_fermer_afficher, "RK_button_fermer_afficher");
  GLADE_HOOKUP_OBJECT (show_parkings_window, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (show_parkings_window, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (show_parkings_window, image6, "image6");
  GLADE_HOOKUP_OBJECT (show_parkings_window, label44, "label44");
  GLADE_HOOKUP_OBJECT (show_parkings_window, label129, "label129");

  return show_parkings_window;
}

GtkWidget*
create_assign_agent_window (void)
{
  GtkWidget *assign_agent_window;
  GtkWidget *fixed14;
  GtkWidget *RK_combobox_affecter_affecter;
  GtkWidget *RK_comboboxentry2_affecter_affecter;
  GtkWidget *RK_button_affecter_affecter;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *label42;
  GtkWidget *RK_button_annuler_affecter;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image5;
  GtkWidget *label43;
  GtkWidget *label_select_agent;
  GtkWidget *label120;
  GtkWidget *RK_label_message_affecter;
  GtkWidget *label38;

  assign_agent_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (assign_agent_window), _("Affecter un agent \303\240 un parking"));
  gtk_window_set_modal (GTK_WINDOW (assign_agent_window), TRUE);

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (assign_agent_window), fixed14);

  RK_combobox_affecter_affecter = gtk_combo_box_new_text ();
  gtk_widget_show (RK_combobox_affecter_affecter);
  gtk_fixed_put (GTK_FIXED (fixed14), RK_combobox_affecter_affecter, 600, 160);
  gtk_widget_set_size_request (RK_combobox_affecter_affecter, 200, 31);

  RK_comboboxentry2_affecter_affecter = gtk_combo_box_new_text ();
  gtk_widget_show (RK_comboboxentry2_affecter_affecter);
  gtk_fixed_put (GTK_FIXED (fixed14), RK_comboboxentry2_affecter_affecter, 599, 250);
  gtk_widget_set_size_request (RK_comboboxentry2_affecter_affecter, 200, 31);

  RK_button_affecter_affecter = gtk_button_new ();
  gtk_widget_show (RK_button_affecter_affecter);
  gtk_fixed_put (GTK_FIXED (fixed14), RK_button_affecter_affecter, 1640, 744);
  gtk_widget_set_size_request (RK_button_affecter_affecter, 90, 29);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (RK_button_affecter_affecter), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("Affecter"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox3), label42, FALSE, FALSE, 0);

  RK_button_annuler_affecter = gtk_button_new ();
  gtk_widget_show (RK_button_annuler_affecter);
  gtk_fixed_put (GTK_FIXED (fixed14), RK_button_annuler_affecter, 1536, 744);
  gtk_widget_set_size_request (RK_button_annuler_affecter, 82, 29);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (RK_button_annuler_affecter), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image5 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox4), image5, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox4), label43, FALSE, FALSE, 0);

  label_select_agent = gtk_label_new_with_mnemonic (_("S\303\251lectionnez un agent"));
  gtk_widget_show (label_select_agent);
  gtk_fixed_put (GTK_FIXED (fixed14), label_select_agent, 328, 256);
  gtk_widget_set_size_request (label_select_agent, 176, 16);

  label120 = gtk_label_new_with_mnemonic (_("S\303\251lectionnez un parking"));
  gtk_widget_show (label120);
  gtk_fixed_put (GTK_FIXED (fixed14), label120, 336, 160);
  gtk_widget_set_size_request (label120, 176, 16);

  RK_label_message_affecter = gtk_label_new ("");
  gtk_widget_show (RK_label_message_affecter);
  gtk_fixed_put (GTK_FIXED (fixed14), RK_label_message_affecter, 512, 568);
  gtk_widget_set_size_request (RK_label_message_affecter, 624, 31);

  label38 = gtk_label_new (_("<span foreground=\"blue\" weight=\"bold\" size=\"xx-large\">S\303\251lectionnez un parking et un agent \303\240 affecter</span>\n"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed14), label38, 480, 32);
  gtk_widget_set_size_request (label38, 784, 64);
  gtk_label_set_use_markup (GTK_LABEL (label38), TRUE);

  g_signal_connect ((gpointer) RK_button_affecter_affecter, "clicked",
                    G_CALLBACK (on_RK_button_affecter_affecter_clicked),
                    NULL);
  g_signal_connect ((gpointer) RK_button_annuler_affecter, "clicked",
                    G_CALLBACK (on_RK_button_annuler_affecter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (assign_agent_window, assign_agent_window, "assign_agent_window");
  GLADE_HOOKUP_OBJECT (assign_agent_window, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (assign_agent_window, RK_combobox_affecter_affecter, "RK_combobox_affecter_affecter");
  GLADE_HOOKUP_OBJECT (assign_agent_window, RK_comboboxentry2_affecter_affecter, "RK_comboboxentry2_affecter_affecter");
  GLADE_HOOKUP_OBJECT (assign_agent_window, RK_button_affecter_affecter, "RK_button_affecter_affecter");
  GLADE_HOOKUP_OBJECT (assign_agent_window, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (assign_agent_window, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (assign_agent_window, image4, "image4");
  GLADE_HOOKUP_OBJECT (assign_agent_window, label42, "label42");
  GLADE_HOOKUP_OBJECT (assign_agent_window, RK_button_annuler_affecter, "RK_button_annuler_affecter");
  GLADE_HOOKUP_OBJECT (assign_agent_window, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (assign_agent_window, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (assign_agent_window, image5, "image5");
  GLADE_HOOKUP_OBJECT (assign_agent_window, label43, "label43");
  GLADE_HOOKUP_OBJECT (assign_agent_window, label_select_agent, "label_select_agent");
  GLADE_HOOKUP_OBJECT (assign_agent_window, label120, "label120");
  GLADE_HOOKUP_OBJECT (assign_agent_window, RK_label_message_affecter, "RK_label_message_affecter");
  GLADE_HOOKUP_OBJECT (assign_agent_window, label38, "label38");

  return assign_agent_window;
}

