/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_add_parking_window (void);
GtkWidget* create_edit_parking_window (void);
GtkWidget* create_main_window (void);
GtkWidget* create_show_parkings_window (void);
GtkWidget* create_assign_agent_window (void);
